version: '2'
services:
  web:
    build: .
    container_name: sistel-web
    ports:
      - "80:8080"
    environment:
      - ENVDB=postgres_db
      - USERDB=postgres
      - PASSDB=root
      - URLLDAP=ldap://000.000.000:389
      - LDAPBASE=$LDAPBASE 
      - USERLDAPDN=$USERLDAPDN 
      - USERLDAP=$USERLDAP 
      - PASSLDAP=$PASSLDAP 
      - ENVMAILHOST=$ENVMAILHOST 
      - ENVMAILPORT=25
      - ENVMAILPROTOCOL=smtp
      - ENVSMTPAUTH=true
      - ENVTLSENABLE=true
      - ENVMAILDEBUG=false
      - ENVMAILTIMEOUT=50000
    volumes:
      - "./:/opt/jboss/wildfly/standalone/deployments/"
    links:
      - postgres_db
  postgres:
    container_name: postgres_db
    image: postgres:9.6
    volumes:
      - .:/code
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data
