version: '2'
services:
  web:
    build: .
    container_name: sistel-web
    ports:
      - "80:8080"
    environment:
      - ENVDB=$ENVDB 
      - USERDB=postgres
      - PASSDB=root
      - URLLDAP=$URLLDAP 
      - LDAPBASE=$LDAPBASE 
      - USERLDAPDN=$USERLDAPDN 
      - USERLDAP=$USERLDAP 
      - PASSLDAP=$PASSLDAP 
      - ENVMAILHOST=$ENVMAILHOST 
      - ENVMAILPORT=$ENVMAILPORT 
      - ENVMAILPROTOCOL=$ENVMAILPROTOCOL 
      - ENVSMTPAUTH=$ENVSMTPAUTH 
      - ENVTLSENABLE=$ENVTLSENABLE 
      - ENVMAILDEBUG=$ENVMAILDEBUG 
      - ENVMAILTIMEOUT=$ENVMAILTIMEOUT
    volumes:
      - "./:/opt/jboss/wildfly/standalone/deployments/"
  postgres:
    container_name: postgres
    image: "postgres:9.6"
    volumes:
      - .:/code
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data
