version: '3'
services:
	sistel-web:
		build: .
		container-name: sistel-web
		ports:
		 - "80:8080"
		environment:
	   - ENVDB=$ENVDB 
	   - USERDB=postgres
	   - PASSDB=root
	   - URLLDAP=$URLLDAP 
	   - LDAPBASE=$LDAPBASE 
	   - USERLDAPDN=$USERLDAPDN 
	   - USERLDAP=$USERLDAP 
	   - PASSLDAP=$PASSLDAP 
	   - ENVMAILHOST=$ENVMAILHOST 
	   - ENVMAILPORT=$ENVMAILPORT 
	   - ENVMAILPROTOCOL=$ENVMAILPROTOCOL 
	   - ENVSMTPAUTH=$ENVSMTPAUTH 
	   - ENVTLSENABLE=$ENVTLSENABLE 
	   - ENVMAILDEBUG=$ENVMAILDEBUG 
	   - ENVMAILTIMEOUT=$ENVMAILTIMEOUT
